// ═══ PRODUCTION SEED DATA: Learning Center ═══

export interface SeedModule {
  title: string; description: string; icon: string; difficulty: string;
  category: string; estimatedTime: string; sortOrder: number;
  lessons: SeedLesson[];
}
export interface SeedLesson {
  title: string; content: string; type: string; estimatedTime: string; sortOrder: number;
  quizQuestions?: SeedQuiz[];
}
export interface SeedQuiz {
  question: string; options: string[]; correctIndex: number; explanation: string; sortOrder: number;
}

export function generateLearningModules(): SeedModule[] {
  return [
    // ── BASICS ──
    { title: 'Stock Market Basics', description: 'Learn the fundamentals of stock markets, exchanges, and how trading works.', icon: '📈', difficulty: 'beginner', category: 'basics', estimatedTime: '45 min', sortOrder: 1, lessons: [
      { title: 'What is the Stock Market?', type: 'article', estimatedTime: '8 min', sortOrder: 1, content: `# What is the Stock Market?\n\nThe stock market is a marketplace where buyers and sellers trade shares of publicly listed companies. It serves as a platform for companies to raise capital and for investors to own a piece of businesses.\n\n## How Does It Work?\n\nWhen a company wants to raise money, it can issue shares through an **Initial Public Offering (IPO)**. Once listed, these shares are traded on stock exchanges like the **National Stock Exchange (NSE)** and **Bombay Stock Exchange (BSE)** in India.\n\n## Key Concepts\n\n### Shares / Stocks\nA share represents a unit of ownership in a company. If a company has 1,000 shares and you own 100, you own 10% of the company.\n\n### Stock Exchanges\n- **NSE (National Stock Exchange)** - India's largest exchange by volume\n- **BSE (Bombay Stock Exchange)** - Asia's oldest exchange (est. 1875)\n\n### Market Participants\n1. **Retail Investors** - Individual investors like you\n2. **Institutional Investors** - Mutual funds, insurance companies\n3. **FIIs** - Foreign Institutional Investors\n4. **DIIs** - Domestic Institutional Investors\n5. **Market Makers** - Provide liquidity\n\n### Market Hours\nIndian stock market operates from **9:15 AM to 3:30 PM IST** on weekdays.\n\n> 💡 **Key Takeaway**: The stock market is essentially a mechanism for efficient price discovery and capital allocation.` },
      { title: 'Types of Markets: Primary vs Secondary', type: 'article', estimatedTime: '6 min', sortOrder: 2, content: `# Primary vs Secondary Market\n\n## Primary Market\nWhere companies issue new securities for the first time.\n- **IPO** (Initial Public Offering) - First time listing\n- **FPO** (Follow-on Public Offering) - Additional shares\n- **Rights Issue** - Offered to existing shareholders\n- **Private Placement** - Sold to select investors\n\n## Secondary Market\nWhere previously issued securities are traded among investors.\n- **Exchanges**: NSE, BSE\n- **Trading**: Buy/sell existing shares\n- **Price Discovery**: Market determines prices\n\n## Key Differences\n| Feature | Primary Market | Secondary Market |\n|---------|---------------|------------------|\n| Securities | New | Existing |\n| Seller | Company | Investors |\n| Price | Fixed by company | Market-driven |\n| Purpose | Raise capital | Provide liquidity |` },
      { title: 'Understanding Market Indices', type: 'article', estimatedTime: '7 min', sortOrder: 3, content: `# Market Indices\n\nA market index tracks the performance of a group of stocks representing a segment of the market.\n\n## Major Indian Indices\n\n### NIFTY 50\n- Top 50 companies on NSE\n- Covers ~65% of free-float market cap\n- Managed by NSE Indices\n\n### SENSEX (BSE 30)\n- Top 30 companies on BSE\n- India's oldest index\n- Managed by BSE\n\n### Other Important Indices\n- **Nifty Bank** - Top banking stocks\n- **Nifty IT** - Technology companies\n- **Nifty Midcap 100** - Mid-size companies\n- **Nifty Smallcap 250** - Smaller companies\n- **India VIX** - Volatility index (fear gauge)\n\n## How Indices Are Calculated\nMost indices use **free-float market capitalization** method:\n\n\`\`\`\nIndex Value = (Sum of free-float market cap of all constituents / Base market cap) × Base value\n\`\`\`\n\n> 💡 If Nifty moves from 24,000 to 24,240, it means a 1% increase in the aggregate value of its 50 constituent stocks.` },
      { title: 'Quiz: Stock Market Basics', type: 'quiz', estimatedTime: '5 min', sortOrder: 4, content: 'Test your knowledge of stock market basics.', quizQuestions: [
        { question: 'What does IPO stand for?', options: ['Initial Price Offering', 'Initial Public Offering', 'Internal Public Order', 'Initial Private Offering'], correctIndex: 1, explanation: 'IPO stands for Initial Public Offering — the first sale of stock by a company to the public.', sortOrder: 1 },
        { question: 'Which is India\'s largest stock exchange by trading volume?', options: ['BSE', 'NSE', 'MCX', 'NCDEX'], correctIndex: 1, explanation: 'The National Stock Exchange (NSE) is India\'s largest stock exchange by trading volume.', sortOrder: 2 },
        { question: 'What does SENSEX track?', options: ['Top 50 NSE stocks', 'Top 30 BSE stocks', 'All BSE stocks', 'Top 100 NSE stocks'], correctIndex: 1, explanation: 'SENSEX (Sensitive Index) tracks the top 30 companies listed on the Bombay Stock Exchange.', sortOrder: 3 },
        { question: 'Indian stock market trading hours are:', options: ['9:00 AM - 3:00 PM', '9:15 AM - 3:30 PM', '10:00 AM - 4:00 PM', '9:30 AM - 4:00 PM'], correctIndex: 1, explanation: 'Indian markets operate from 9:15 AM to 3:30 PM IST on business days.', sortOrder: 4 },
      ]},
    ]},

    // ── CANDLESTICK PATTERNS ──
    { title: 'Candlestick Patterns', description: 'Master Japanese candlestick charting to identify trend reversals and continuations.', icon: '🕯️', difficulty: 'intermediate', category: 'technical', estimatedTime: '60 min', sortOrder: 2, lessons: [
      { title: 'Reading Candlestick Charts', type: 'article', estimatedTime: '8 min', sortOrder: 1, content: `# Reading Candlestick Charts\n\nA candlestick shows four prices: **Open, High, Low, Close (OHLC)**.\n\n## Anatomy of a Candle\n\n\`\`\`\n   │ ← Upper Shadow (Wick)\n ┌─┤\n │ │ ← Body (filled = bearish, hollow = bullish)\n └─┤\n   │ ← Lower Shadow (Tail)\n\`\`\`\n\n### Bullish Candle (Green/White)\n- Close > Open\n- Shows buying pressure\n\n### Bearish Candle (Red/Black)\n- Close < Open\n- Shows selling pressure\n\n## What Shadows Tell You\n- **Long upper shadow**: Sellers pushed price down from highs\n- **Long lower shadow**: Buyers stepped in at lows\n- **No shadows**: Strong conviction in direction\n\n## Body Size Matters\n- **Large body**: Strong momentum\n- **Small body**: Indecision\n- **No body (Doji)**: Perfect equilibrium` },
      { title: 'Bullish Reversal Patterns', type: 'article', estimatedTime: '10 min', sortOrder: 2, content: `# Bullish Reversal Patterns\n\nThese patterns appear at the bottom of downtrends and signal a potential reversal upward.\n\n## 1. Hammer 🔨\n- Small body at top, long lower shadow (2x+ body)\n- Appears after a downtrend\n- **Signal**: Buyers are stepping in\n- **Confirmation**: Next day closes green\n- **Success Rate**: ~60%\n\n## 2. Morning Star ⭐\nA three-candle pattern:\n1. Large bearish candle\n2. Small-bodied candle (gap down)\n3. Large bullish candle closing above midpoint of candle 1\n- **Success Rate**: ~78%\n\n## 3. Bullish Engulfing\n- Bearish candle followed by a larger bullish candle\n- The bullish candle completely \"engulfs\" the previous\n- **Signal**: Strong buying momentum\n- **Success Rate**: ~63%\n\n## 4. Piercing Pattern\n- Bearish candle + bullish candle that opens below prior low but closes above 50% of prior body\n- **Success Rate**: ~64%\n\n## 5. Three White Soldiers\n- Three consecutive long bullish candles\n- Each opens within previous body, closes near high\n- **Signal**: Very strong bullish momentum\n- **Success Rate**: ~82%\n\n> ⚠️ Always confirm patterns with volume and other indicators.` },
      { title: 'Bearish Reversal Patterns', type: 'article', estimatedTime: '10 min', sortOrder: 3, content: `# Bearish Reversal Patterns\n\n## 1. Shooting Star ⭐\n- Small body at bottom, long upper shadow\n- Appears after an uptrend\n- **Signal**: Sellers are pushing back\n- **Success Rate**: ~59%\n\n## 2. Evening Star\nOpposite of Morning Star:\n1. Large bullish candle\n2. Small-bodied candle (gap up)\n3. Large bearish candle closing below midpoint of candle 1\n- **Success Rate**: ~72%\n\n## 3. Bearish Engulfing\n- Bullish candle followed by larger bearish candle\n- **Signal**: Strong selling pressure\n- **Success Rate**: ~79%\n\n## 4. Dark Cloud Cover\n- Bullish candle + bearish candle opening above high but closing below 50% of prior body\n- **Success Rate**: ~60%\n\n## 5. Three Black Crows\n- Three consecutive long bearish candles\n- Each opens within prior body, closes near low\n- **Signal**: Strong bearish momentum\n- **Success Rate**: ~78%\n\n## 6. Hanging Man\n- Same shape as Hammer but at top of uptrend\n- Long lower shadow, small body near top\n- **Signal**: Momentum weakening` },
      { title: 'Quiz: Candlestick Patterns', type: 'quiz', estimatedTime: '5 min', sortOrder: 4, content: 'Test your candlestick pattern recognition.', quizQuestions: [
        { question: 'A Hammer pattern appears at the:', options: ['Top of an uptrend', 'Bottom of a downtrend', 'Middle of a trend', 'It doesn\'t matter'], correctIndex: 1, explanation: 'Hammers are bullish reversal patterns that appear at the bottom of downtrends.', sortOrder: 1 },
        { question: 'Which pattern has the highest success rate?', options: ['Hammer (~60%)', 'Three White Soldiers (~82%)', 'Shooting Star (~59%)', 'Doji (~50%)'], correctIndex: 1, explanation: 'Three White Soldiers has one of the highest success rates at approximately 82%.', sortOrder: 2 },
        { question: 'A Doji candle indicates:', options: ['Strong bullish momentum', 'Strong bearish momentum', 'Market indecision', 'A gap'], correctIndex: 2, explanation: 'A Doji forms when open and close are nearly equal, indicating indecision between buyers and sellers.', sortOrder: 3 },
      ]},
    ]},

    // ── TECHNICAL INDICATORS ──
    { title: 'Moving Averages (SMA & EMA)', description: 'Learn how Simple and Exponential Moving Averages help identify trends.', icon: '📊', difficulty: 'intermediate', category: 'technical', estimatedTime: '40 min', sortOrder: 3, lessons: [
      { title: 'Simple Moving Average (SMA)', type: 'article', estimatedTime: '10 min', sortOrder: 1, content: `# Simple Moving Average (SMA)\n\nSMA calculates the arithmetic mean of closing prices over a period.\n\n## Formula\n\`\`\`\nSMA(n) = (P₁ + P₂ + ... + Pₙ) / n\n\`\`\`\nWhere P = closing price, n = period\n\n## Common Periods\n- **SMA(20)**: Short-term trend (1 month)\n- **SMA(50)**: Medium-term trend\n- **SMA(200)**: Long-term trend\n\n## Trading Signals\n\n### Golden Cross 🟢\nSMA(50) crosses above SMA(200) → **Bullish signal**\n\n### Death Cross 🔴\nSMA(50) crosses below SMA(200) → **Bearish signal**\n\n### Price vs SMA\n- Price above SMA → Bullish\n- Price below SMA → Bearish\n- Price bouncing off SMA → Support/Resistance\n\n## Limitations\n- Lagging indicator (uses past data)\n- Equal weight to all prices\n- Can generate false signals in sideways markets` },
      { title: 'Exponential Moving Average (EMA)', type: 'article', estimatedTime: '10 min', sortOrder: 2, content: `# Exponential Moving Average (EMA)\n\nEMA gives more weight to recent prices, making it more responsive than SMA.\n\n## Formula\n\`\`\`\nEMA = Price(today) × k + EMA(yesterday) × (1-k)\nk = 2 / (N + 1)\n\`\`\`\n\n## EMA vs SMA\n| Feature | SMA | EMA |\n|---------|-----|-----|\n| Responsiveness | Slow | Fast |\n| Lag | More | Less |\n| Whipsaws | Fewer | More |\n| Best for | Long-term trends | Short-term trading |\n\n## Popular EMA Periods\n- **EMA(9)**: Very short-term\n- **EMA(12)**: Used in MACD calculation\n- **EMA(21)**: Swing trading\n- **EMA(26)**: Used in MACD calculation\n- **EMA(50)**: Medium-term\n\n## Trading Strategy: EMA Crossover\n1. Plot EMA(9) and EMA(21)\n2. **Buy** when EMA(9) crosses above EMA(21)\n3. **Sell** when EMA(9) crosses below EMA(21)\n4. Use volume to confirm signals` },
      { title: 'Quiz: Moving Averages', type: 'quiz', estimatedTime: '5 min', sortOrder: 3, content: 'Test your moving average knowledge.', quizQuestions: [
        { question: 'A Golden Cross occurs when:', options: ['SMA(200) crosses above SMA(50)', 'SMA(50) crosses above SMA(200)', 'Price crosses above SMA(50)', 'EMA(9) crosses above EMA(21)'], correctIndex: 1, explanation: 'A Golden Cross is when the 50-day SMA crosses above the 200-day SMA — a strong bullish signal.', sortOrder: 1 },
        { question: 'Which gives more weight to recent prices?', options: ['SMA', 'EMA', 'Both equally', 'Neither'], correctIndex: 1, explanation: 'EMA (Exponential Moving Average) gives more weight to recent prices, making it more responsive to new data.', sortOrder: 2 },
      ]},
    ]},

    // ── RSI ──
    { title: 'RSI (Relative Strength Index)', description: 'Master the RSI momentum oscillator for identifying overbought and oversold conditions.', icon: '🔄', difficulty: 'intermediate', category: 'technical', estimatedTime: '35 min', sortOrder: 4, lessons: [
      { title: 'Understanding RSI', type: 'article', estimatedTime: '12 min', sortOrder: 1, content: `# Relative Strength Index (RSI)\n\nRSI measures the speed and magnitude of price changes to evaluate overbought/oversold conditions.\n\n## Formula\n\`\`\`\nRSI = 100 - [100 / (1 + RS)]\nRS = Average Gain / Average Loss (over N periods)\nDefault period: 14\n\`\`\`\n\n## Interpretation\n\n### Overbought (RSI > 70)\n- Stock may be overvalued\n- Potential reversal or pullback\n- ⚠️ In strong uptrends, RSI can stay above 70 for extended periods\n\n### Oversold (RSI < 30)\n- Stock may be undervalued\n- Potential bounce or reversal\n- ⚠️ In strong downtrends, RSI can stay below 30\n\n### Neutral Zone (30-70)\n- No extreme signals\n- Look for divergences\n\n## Advanced RSI Signals\n\n### Bullish Divergence\nPrice makes lower low, but RSI makes higher low → **Buy signal**\n\n### Bearish Divergence\nPrice makes higher high, but RSI makes lower high → **Sell signal**\n\n### RSI Swing Rejection\n1. RSI enters overbought/oversold\n2. Crosses back below/above 70/30\n3. Makes a pullback without re-entering extreme zone\n4. Breaks its most recent high/low\n\n> 💡 RSI works best in ranging markets. In strong trends, adjust levels to 80/20.` },
      { title: 'Quiz: RSI', type: 'quiz', estimatedTime: '5 min', sortOrder: 2, content: 'Test RSI knowledge.', quizQuestions: [
        { question: 'RSI above 70 indicates:', options: ['Oversold', 'Overbought', 'Neutral', 'Bullish divergence'], correctIndex: 1, explanation: 'RSI above 70 is considered overbought, suggesting the stock may be due for a correction.', sortOrder: 1 },
        { question: 'The default RSI period is:', options: ['7', '14', '21', '28'], correctIndex: 1, explanation: 'The standard RSI uses 14 periods, as originally recommended by J. Welles Wilder.', sortOrder: 2 },
      ]},
    ]},

    // ── MACD ──
    { title: 'MACD (Moving Average Convergence Divergence)', description: 'Learn to use MACD for identifying trend changes and momentum shifts.', icon: '📉', difficulty: 'intermediate', category: 'technical', estimatedTime: '35 min', sortOrder: 5, lessons: [
      { title: 'MACD Explained', type: 'article', estimatedTime: '12 min', sortOrder: 1, content: `# MACD\n\n## Components\n1. **MACD Line** = EMA(12) - EMA(26)\n2. **Signal Line** = EMA(9) of MACD Line\n3. **Histogram** = MACD Line - Signal Line\n\n## Trading Signals\n\n### Signal Line Crossover\n- **Bullish**: MACD crosses above Signal Line\n- **Bearish**: MACD crosses below Signal Line\n\n### Zero Line Crossover\n- **Bullish**: MACD crosses above zero\n- **Bearish**: MACD crosses below zero\n\n### Divergence\n- **Bullish**: Price lower low + MACD higher low\n- **Bearish**: Price higher high + MACD lower high\n\n### Histogram Analysis\n- Growing bars = Strengthening momentum\n- Shrinking bars = Weakening momentum\n- Color change = Potential crossover coming\n\n## Best Practices\n- Use on daily/weekly charts\n- Combine with RSI for confirmation\n- Don't use in choppy, sideways markets\n- Adjust settings for different timeframes` },
      { title: 'Quiz: MACD', type: 'quiz', estimatedTime: '5 min', sortOrder: 2, content: 'Test MACD knowledge.', quizQuestions: [
        { question: 'MACD Line is calculated as:', options: ['EMA(26) - EMA(12)', 'EMA(12) - EMA(26)', 'SMA(12) - SMA(26)', 'EMA(9) - EMA(21)'], correctIndex: 1, explanation: 'MACD Line = EMA(12) - EMA(26). It measures the difference between short and long-term moving averages.', sortOrder: 1 },
      ]},
    ]},

    // ── BOLLINGER BANDS ──
    { title: 'Bollinger Bands', description: 'Use volatility-based bands to identify potential breakouts and mean reversions.', icon: '📐', difficulty: 'intermediate', category: 'technical', estimatedTime: '30 min', sortOrder: 6, lessons: [
      { title: 'Bollinger Bands Strategy', type: 'article', estimatedTime: '12 min', sortOrder: 1, content: `# Bollinger Bands\n\nCreated by John Bollinger, these bands measure volatility around a moving average.\n\n## Calculation\n- **Middle Band**: SMA(20)\n- **Upper Band**: SMA(20) + 2 × Standard Deviation\n- **Lower Band**: SMA(20) - 2 × Standard Deviation\n\n## Key Concepts\n\n### Bollinger Squeeze\nWhen bands contract (low volatility), a breakout is imminent.\n- Squeeze → Expansion = Big move coming\n- Direction of breakout determines trade direction\n\n### Bollinger Bounce (Mean Reversion)\n- Price touching lower band → Potential buy\n- Price touching upper band → Potential sell\n- Works best in ranging markets\n\n### Walking the Bands\nIn strong trends, price can "walk" along a band:\n- Walking upper band = Strong uptrend\n- Walking lower band = Strong downtrend\n\n### %B Indicator\n\`\`\`\n%B = (Price - Lower Band) / (Upper Band - Lower Band)\n\`\`\`\n- %B > 1: Above upper band (overbought)\n- %B < 0: Below lower band (oversold)\n- %B = 0.5: At middle band` },
      { title: 'Quiz: Bollinger Bands', type: 'quiz', estimatedTime: '5 min', sortOrder: 2, content: 'Test your knowledge.', quizQuestions: [
        { question: 'A Bollinger Squeeze indicates:', options: ['High volatility', 'Low volatility before a breakout', 'Bearish reversal', 'End of trend'], correctIndex: 1, explanation: 'A squeeze occurs when bands contract, indicating low volatility. This often precedes a significant price move.', sortOrder: 1 },
      ]},
    ]},

    // ── VWAP ──
    { title: 'VWAP (Volume Weighted Average Price)', description: 'Learn to use VWAP for intraday trading and institutional price analysis.', icon: '💹', difficulty: 'intermediate', category: 'technical', estimatedTime: '25 min', sortOrder: 7, lessons: [
      { title: 'VWAP Trading', type: 'article', estimatedTime: '10 min', sortOrder: 1, content: `# VWAP\n\nVWAP represents the average price weighted by volume throughout the trading day.\n\n## Formula\n\`\`\`\nVWAP = Cumulative(Price × Volume) / Cumulative(Volume)\n\`\`\`\n\n## Trading Rules\n- **Price > VWAP**: Bullish bias, look for longs\n- **Price < VWAP**: Bearish bias, look for shorts\n- **Price = VWAP**: Fair value zone\n\n## VWAP as Support/Resistance\nInstitutional traders use VWAP to execute large orders:\n- They buy below VWAP (getting a discount)\n- They sell above VWAP (getting premium)\n\nThis creates natural support/resistance at VWAP level.\n\n## Best Practices\n- Reset daily (intraday indicator)\n- Most effective in first 2 hours of trading\n- Combine with volume profile for confirmation\n- Not reliable in pre-market or after-hours` },
    ]},

    // ── SUPPORT & RESISTANCE ──
    { title: 'Support & Resistance', description: 'Identify key price levels where stocks are likely to reverse or pause.', icon: '🎯', difficulty: 'beginner', category: 'technical', estimatedTime: '40 min', sortOrder: 8, lessons: [
      { title: 'Finding Support & Resistance', type: 'article', estimatedTime: '12 min', sortOrder: 1, content: `# Support & Resistance\n\n## Support\nA price level where buying interest is strong enough to prevent further decline.\n- Previous lows\n- Moving averages\n- Round numbers (₹100, ₹500, ₹1000)\n- Fibonacci retracement levels\n\n## Resistance\nA price level where selling interest prevents further rise.\n- Previous highs\n- All-time highs\n- Moving averages\n- Psychological levels\n\n## Role Reversal\n> Once broken, support becomes resistance and vice versa.\n\nThis is one of the most important concepts in technical analysis.\n\n## How to Draw Support/Resistance\n1. Identify areas where price reversed multiple times\n2. Use horizontal lines (not just points)\n3. The more touches, the stronger the level\n4. Recent levels are more relevant\n5. Higher timeframe levels are stronger\n\n## Trading Strategies\n- **Bounce Trading**: Buy at support, sell at resistance\n- **Breakout Trading**: Buy when resistance breaks with volume\n- **Breakdown Trading**: Sell when support breaks with volume` },
      { title: 'Quiz: Support & Resistance', type: 'quiz', estimatedTime: '5 min', sortOrder: 2, content: 'Test your knowledge.', quizQuestions: [
        { question: 'When support breaks, it often becomes:', options: ['Stronger support', 'Resistance', 'Irrelevant', 'A trendline'], correctIndex: 1, explanation: 'This is called role reversal — broken support becomes resistance and broken resistance becomes support.', sortOrder: 1 },
      ]},
    ]},

    // ── VOLUME ANALYSIS ──
    { title: 'Volume Analysis', description: 'Learn how volume confirms trends and signals reversals.', icon: '📊', difficulty: 'intermediate', category: 'technical', estimatedTime: '30 min', sortOrder: 9, lessons: [
      { title: 'Volume Price Analysis', type: 'article', estimatedTime: '12 min', sortOrder: 1, content: `# Volume Analysis\n\nVolume is the number of shares traded. It confirms the strength of price moves.\n\n## Volume + Price Rules\n\n| Price | Volume | Signal |\n|-------|--------|--------|\n| ↑ Up | ↑ High | Healthy uptrend ✅ |\n| ↑ Up | ↓ Low | Weak rally ⚠️ |\n| ↓ Down | ↑ High | Strong selling 🔴 |\n| ↓ Down | ↓ Low | Weak decline (may reverse) |\n\n## Key Volume Patterns\n\n### Volume Climax\nExtremely high volume after extended move → Potential exhaustion/reversal\n\n### Volume Dry-up\nVery low volume after a move → Waiting for catalyst\n\n### Accumulation\nFlat price + high volume = Smart money buying quietly\n\n### Distribution\nFlat price + high volume = Smart money selling quietly\n\n## OBV (On-Balance Volume)\n\`\`\`\nIf Close > Previous Close: OBV += Volume\nIf Close < Previous Close: OBV -= Volume\n\`\`\`\nOBV rising = Accumulation\nOBV falling = Distribution` },
    ]},

    // ── FUNDAMENTAL ANALYSIS ──
    { title: 'Fundamental Analysis', description: 'Analyze financial statements, ratios, and business quality.', icon: '📋', difficulty: 'intermediate', category: 'fundamental', estimatedTime: '90 min', sortOrder: 10, lessons: [
      { title: 'Income Statement Analysis', type: 'article', estimatedTime: '15 min', sortOrder: 1, content: `# Income Statement\n\nThe income statement shows revenue, expenses, and profit over a period.\n\n## Key Line Items\n\n### Revenue (Top Line)\n- Total sales/income\n- Look for consistent growth\n- Compare with industry peers\n\n### Operating Profit (EBITDA)\n- Revenue - Operating Expenses\n- Shows operational efficiency\n- **Operating Margin** = EBITDA / Revenue\n\n### Net Profit (Bottom Line)\n- After all expenses, taxes, interest\n- **Net Margin** = Net Profit / Revenue\n- Compare margins across quarters\n\n### EPS (Earnings Per Share)\n- Net Profit / Total Shares Outstanding\n- Most watched metric by analysts\n- Diluted EPS accounts for stock options\n\n## What to Look For\n✅ Consistent revenue growth (>10% YoY)\n✅ Expanding margins\n✅ Growing EPS\n✅ Revenue quality (recurring vs one-time)\n❌ Declining margins\n❌ Revenue growing but profits falling\n❌ Large one-time gains inflating profits` },
      { title: 'Balance Sheet & Cash Flow', type: 'article', estimatedTime: '15 min', sortOrder: 2, content: `# Balance Sheet & Cash Flow\n\n## Balance Sheet\nSnapshot of assets, liabilities, and equity at a point in time.\n\n### Key Metrics\n- **Debt/Equity Ratio** = Total Debt / Shareholders' Equity\n  - < 1: Conservative\n  - 1-2: Moderate\n  - > 2: Highly leveraged\n\n- **Current Ratio** = Current Assets / Current Liabilities\n  - > 1.5: Good liquidity\n  - < 1: Liquidity risk\n\n- **Book Value** = Total Assets - Total Liabilities\n\n## Cash Flow Statement\nTracks actual cash movement.\n\n### Three Types\n1. **Operating Cash Flow** (most important)\n   - Cash from core business\n   - Should be positive and growing\n\n2. **Investing Cash Flow**\n   - Capex, acquisitions\n   - Usually negative (investing in growth)\n\n3. **Financing Cash Flow**\n   - Debt, dividends, buybacks\n   - Varies by company stage\n\n### Free Cash Flow\n\`\`\`\nFCF = Operating Cash Flow - Capital Expenditure\n\`\`\`\nWarren Buffett's favorite metric!` },
      { title: 'Valuation Ratios', type: 'article', estimatedTime: '15 min', sortOrder: 3, content: `# Valuation Ratios\n\n## P/E Ratio (Price to Earnings)\n\`\`\`\nP/E = Market Price / EPS\n\`\`\`\n- Low P/E: Potentially undervalued\n- High P/E: Growth expectations\n- Compare within same sector\n- Indian market average: ~22x\n\n## P/B Ratio (Price to Book)\n\`\`\`\nP/B = Market Price / Book Value per Share\n\`\`\`\n- < 1: Trading below asset value\n- Useful for banking stocks\n\n## PEG Ratio\n\`\`\`\nPEG = P/E / Earnings Growth Rate\n\`\`\`\n- < 1: Undervalued relative to growth\n- = 1: Fairly valued\n- > 1: Overvalued relative to growth\n\n## ROE (Return on Equity)\n\`\`\`\nROE = Net Profit / Shareholders' Equity × 100\n\`\`\`\n- > 15%: Good\n- > 20%: Excellent\n- Consistently high ROE = Quality company\n\n## ROCE (Return on Capital Employed)\n\`\`\`\nROCE = EBIT / Capital Employed × 100\n\`\`\`\n- Better than ROE for capital-intensive businesses\n- > 15%: Good capital allocation\n\n## Dividend Yield\n\`\`\`\nDividend Yield = Annual Dividend / Market Price × 100\n\`\`\`\n- Stable dividend = Mature, profitable company\n- High yield + low payout ratio = Sustainable` },
      { title: 'Quiz: Fundamental Analysis', type: 'quiz', estimatedTime: '5 min', sortOrder: 4, content: 'Test your fundamentals.', quizQuestions: [
        { question: 'A PEG ratio below 1 indicates:', options: ['Overvalued stock', 'Undervalued relative to growth', 'High debt', 'Low liquidity'], correctIndex: 1, explanation: 'PEG < 1 means the stock is potentially undervalued considering its earnings growth rate.', sortOrder: 1 },
        { question: 'Which cash flow is most important for evaluating business quality?', options: ['Investing Cash Flow', 'Financing Cash Flow', 'Operating Cash Flow', 'Free Cash Flow'], correctIndex: 2, explanation: 'Operating Cash Flow shows the cash generated from the core business — the most reliable indicator of business health.', sortOrder: 2 },
        { question: 'ROE above 20% is considered:', options: ['Poor', 'Average', 'Good', 'Excellent'], correctIndex: 3, explanation: 'ROE > 20% is considered excellent and indicates the company generates strong returns on shareholder equity.', sortOrder: 3 },
      ]},
    ]},

    // ── More modules (shorter definitions) ──
    { title: 'Price Action Trading', description: 'Trade using raw price movements without indicators.', icon: '🎯', difficulty: 'advanced', category: 'trading', estimatedTime: '50 min', sortOrder: 11, lessons: [
      { title: 'Price Action Fundamentals', type: 'article', estimatedTime: '15 min', sortOrder: 1, content: `# Price Action Trading\n\nPrice action is trading based on raw price movements. No indicators needed.\n\n## Core Principles\n1. Price reflects all available information\n2. History tends to repeat (patterns)\n3. Market structure defines trend\n\n## Key Concepts\n\n### Higher Highs & Higher Lows (Uptrend)\nEach swing high is higher than the previous, and each swing low is higher.\n\n### Lower Highs & Lower Lows (Downtrend)\nEach swing high is lower, and each swing low is lower.\n\n### Inside Bars\nA candle entirely within the range of the previous candle → Consolidation/continuation.\n\n### Pin Bars\nCandles with long wicks showing rejection of a level.\n\n### Engulfing Bars\nA candle that completely covers the previous → Strong reversal signal.\n\n## Trading Strategy\n1. Identify market structure (trend)\n2. Wait for pullback to key level\n3. Look for price action signal (pin bar, engulfing)\n4. Enter with stop loss below/above signal candle\n5. Target next structure level` },
    ]},
    { title: 'Swing Trading Strategies', description: 'Hold positions for days to weeks, capturing medium-term moves.', icon: '🔄', difficulty: 'intermediate', category: 'trading', estimatedTime: '45 min', sortOrder: 12, lessons: [
      { title: 'Swing Trading Guide', type: 'article', estimatedTime: '15 min', sortOrder: 1, content: `# Swing Trading\n\nHolding for 2-10 days to capture price "swings."\n\n## Setup\n- Timeframe: Daily chart\n- Indicators: EMA(21), RSI(14), Volume\n- Watchlist: 20-30 liquid stocks\n\n## Entry Criteria\n1. Stock in clear uptrend (above EMA 21)\n2. Pullback to EMA 21 or support\n3. RSI between 40-55 (not overbought)\n4. Bullish candle pattern at support\n5. Above-average volume\n\n## Exit Rules\n- **Stop Loss**: Below swing low or 2% below entry\n- **Target**: Previous high or 1.5:1 risk-reward\n- **Trail**: Move stop to breakeven after 1R profit\n\n## Position Sizing\n\`\`\`\nPosition Size = (Capital × Risk%) / (Entry - Stop Loss)\nExample: ₹5,00,000 × 1% / ₹20 gap = 250 shares\n\`\`\`\n\n## Common Mistakes\n❌ Overtrading\n❌ Moving stop loss further away\n❌ No plan before entry\n❌ Trading against the trend` },
    ]},
    { title: 'Intraday Trading', description: 'Master techniques for buying and selling within the same trading day.', icon: '⚡', difficulty: 'advanced', category: 'trading', estimatedTime: '50 min', sortOrder: 13, lessons: [
      { title: 'Intraday Trading Strategies', type: 'article', estimatedTime: '15 min', sortOrder: 1, content: `# Intraday Trading\n\nBuying and selling within the same day. No overnight positions.\n\n## Popular Strategies\n\n### Opening Range Breakout (ORB)\n1. Mark the high/low of first 15-30 minutes\n2. Buy breakout above high with volume\n3. Sell breakdown below low with volume\n4. Stop loss at opposite end of range\n\n### VWAP Trading\n- Buy above VWAP, sell below VWAP\n- Use VWAP as dynamic support/resistance\n\n### Gap Trading\n- **Gap Up Buy**: Buy stocks gapping up 2-5% with volume\n- **Gap Fill Short**: Short overextended gaps expecting fill\n\n## Risk Management\n- Never risk > 1-2% of capital per trade\n- Daily loss limit: 3% of capital\n- Maximum 3-4 trades per day\n- Always use stop loss orders\n\n## Essential Tools\n- Level 2 data / Market depth\n- 1-min and 5-min charts\n- VWAP, EMA(9), EMA(21)\n- Volume profile\n- News alerts` },
    ]},
    { title: 'Mutual Funds & ETFs', description: 'Understand mutual fund categories, selection criteria, and ETF investing.', icon: '🏦', difficulty: 'beginner', category: 'investing', estimatedTime: '40 min', sortOrder: 14, lessons: [
      { title: 'Types of Mutual Funds', type: 'article', estimatedTime: '12 min', sortOrder: 1, content: `# Mutual Fund Categories\n\n## Equity Funds\n- **Large Cap**: Top 100 companies (lower risk)\n- **Mid Cap**: 101-250 companies (moderate risk)\n- **Small Cap**: 251+ companies (higher risk)\n- **Multi/Flexi Cap**: Across market caps\n- **ELSS**: Tax-saving, 3-year lock-in\n- **Sectoral**: Specific sector exposure\n- **Index**: Track an index passively\n\n## Debt Funds\n- **Liquid**: Very short-term, low risk\n- **Short Duration**: 1-3 year maturity\n- **Corporate Bond**: Investment-grade bonds\n- **Gilt**: Government securities\n- **Dynamic Bond**: Flexible duration\n\n## Hybrid Funds\n- **Aggressive Hybrid**: 65-80% equity\n- **Balanced Advantage**: Dynamic allocation\n- **Conservative Hybrid**: 75-90% debt\n\n## How to Select\n1. Define your goal and time horizon\n2. Assess risk tolerance\n3. Check 5-year & 10-year returns\n4. Compare expense ratios\n5. Verify fund manager track record\n6. Prefer Direct plans over Regular\n7. Look for consistency, not just returns` },
      { title: 'SIP vs Lumpsum', type: 'article', estimatedTime: '8 min', sortOrder: 2, content: `# SIP vs Lumpsum\n\n## SIP (Systematic Investment Plan)\nInvest fixed amount regularly (monthly/weekly).\n\n### Advantages\n- **Rupee Cost Averaging**: Buy more units when price is low\n- **Disciplined investing**: Automated, removes emotion\n- **No timing needed**: Works in all markets\n- **Starts small**: Even ₹500/month\n\n### SIP Returns Formula\n\`\`\`\nFV = P × [(1+r)^n - 1] / r × (1+r)\nP = Monthly SIP amount\nr = Monthly return rate\nn = Number of months\n\`\`\`\n\n## Lumpsum\nInvest entire amount at once.\n\n### When to Use\n- After receiving a bonus\n- When markets have corrected significantly\n- Long time horizon (7+ years)\n\n## Comparison\n| Scenario | SIP Wins | Lumpsum Wins |\n|----------|----------|-------------|\n| Falling market | ✅ | ❌ |\n| Rising market | ❌ | ✅ |\n| Volatile market | ✅ | ❌ |\n| Long-term | Tie | Tie |\n\n> 💡 Best approach: SIP for regular income + Lumpsum during corrections.` },
    ]},
    { title: 'Risk Management', description: 'Protect your capital with proven risk management techniques.', icon: '🛡️', difficulty: 'intermediate', category: 'trading', estimatedTime: '45 min', sortOrder: 15, lessons: [
      { title: 'Position Sizing & Risk Control', type: 'article', estimatedTime: '15 min', sortOrder: 1, content: `# Risk Management\n\nThe #1 skill that separates profitable traders from losing ones.\n\n## The 1% Rule\nNever risk more than 1% of your capital on a single trade.\n\n\`\`\`\nCapital: ₹5,00,000\nMax Risk per Trade: ₹5,000 (1%)\nEntry: ₹100\nStop Loss: ₹95 (₹5 risk per share)\nMax Shares: 5,000 / 5 = 1,000 shares\n\`\`\`\n\n## Risk-Reward Ratio\nAlways target at least 1:2 risk-reward.\n- Risk ₹5 to make ₹10 → 1:2 ratio\n- Even with 40% win rate, you're profitable!\n\n## Portfolio Risk\n- Don't put >5% of portfolio in single stock\n- Diversify across 15-25 stocks\n- Diversify across sectors\n- Keep 10-20% in cash for opportunities\n\n## Stop Loss Types\n1. **Fixed**: Set % below entry\n2. **ATR-based**: 2× ATR below entry\n3. **Structure-based**: Below support/swing low\n4. **Trailing**: Moves up as price rises\n\n## Common Mistakes\n❌ No stop loss\n❌ Averaging down losers\n❌ Risking too much on "sure things"\n❌ Revenge trading after losses` },
    ]},
    { title: 'Trading Psychology', description: 'Master the mental game of trading — fear, greed, and discipline.', icon: '🧠', difficulty: 'advanced', category: 'trading', estimatedTime: '40 min', sortOrder: 16, lessons: [
      { title: 'Mental Framework for Trading', type: 'article', estimatedTime: '15 min', sortOrder: 1, content: `# Trading Psychology\n\n## The Two Enemies\n\n### Fear 😰\n- Fear of losing money\n- Fear of missing out (FOMO)\n- Fear of being wrong\n\n### Greed 🤑\n- Not taking profits\n- Overleveraging\n- Trading too frequently\n\n## Cognitive Biases\n1. **Confirmation Bias**: Seeking info that supports your position\n2. **Loss Aversion**: Holding losers too long, cutting winners too early\n3. **Recency Bias**: Overweighting recent events\n4. **Anchoring**: Fixed on entry price\n5. **Sunk Cost Fallacy**: "I've already lost so much, can't sell now"\n\n## Building Discipline\n1. **Trading Journal**: Record every trade + emotions\n2. **Pre-trade Checklist**: Never trade without a plan\n3. **Post-trade Review**: Learn from wins AND losses\n4. **Daily Routine**: Fixed analysis + trading time\n5. **Accept Losses**: They are cost of doing business\n\n> "The goal of a successful trader is to make the best trades. Money is secondary." — Alexander Elder` },
    ]},
    { title: 'Portfolio Management', description: 'Build and manage a diversified investment portfolio for long-term wealth.', icon: '💼', difficulty: 'intermediate', category: 'investing', estimatedTime: '50 min', sortOrder: 17, lessons: [
      { title: 'Building a Portfolio', type: 'article', estimatedTime: '15 min', sortOrder: 1, content: `# Portfolio Construction\n\n## Asset Allocation by Age\nA simple rule: **Equity allocation = 100 - Your Age**\n\n| Age | Equity | Debt | Gold |\n|-----|--------|------|------|\n| 25 | 75% | 20% | 5% |\n| 35 | 65% | 25% | 10% |\n| 45 | 55% | 35% | 10% |\n| 55 | 40% | 45% | 15% |\n\n## Equity Portfolio Structure\n- **Core (60-70%)**: Large cap stocks/funds\n- **Growth (20-30%)**: Mid/small cap exposure\n- **Tactical (10%)**: Sectoral/thematic bets\n\n## Diversification Rules\n- Minimum 15 stocks, maximum 25\n- No single stock > 10% of portfolio\n- No single sector > 25%\n- Include 3-5 sectors minimum\n\n## When to Rebalance\n- Quarterly review\n- Rebalance when allocation drifts >5%\n- Tax-efficient rebalancing\n- Don't rebalance too frequently` },
    ]},
    { title: 'Stock Market Taxation', description: 'Understand capital gains tax, STT, and tax-saving strategies in India.', icon: '📝', difficulty: 'beginner', category: 'investing', estimatedTime: '35 min', sortOrder: 18, lessons: [
      { title: 'Tax on Stock Market Gains', type: 'article', estimatedTime: '12 min', sortOrder: 1, content: `# Stock Market Taxation (India)\n\n## Capital Gains Tax\n\n### Short-Term Capital Gains (STCG)\n- Holding < 1 year (equity)\n- Tax Rate: **15%** (+ surcharge + cess)\n\n### Long-Term Capital Gains (LTCG)\n- Holding > 1 year (equity)\n- Tax Rate: **10%** on gains above ₹1 lakh\n- No indexation benefit for equity\n\n## Securities Transaction Tax (STT)\n- Paid on every buy/sell transaction\n- Delivery: 0.1% on both buy & sell\n- Intraday: 0.025% on sell side only\n\n## Tax-Saving Strategies\n1. **ELSS Funds**: Save up to ₹46,800 tax (Section 80C)\n2. **Tax-Loss Harvesting**: Book losses to offset gains\n3. **Hold for 1+ year**: LTCG vs STCG advantage\n4. **Stagger profit booking**: Stay under ₹1 lakh LTCG\n5. **NPS**: Additional ₹50,000 deduction (Section 80CCD)\n\n## Dividend Tax\n- Taxed at your income tax slab rate\n- TDS of 10% if dividend > ₹5,000` },
    ]},
    { title: 'Options Trading Basics', description: 'Introduction to call and put options, strategies, and the Greeks.', icon: '📊', difficulty: 'advanced', category: 'trading', estimatedTime: '60 min', sortOrder: 19, lessons: [
      { title: 'Understanding Options', type: 'article', estimatedTime: '15 min', sortOrder: 1, content: `# Options Basics\n\n## What is an Option?\nA contract giving the right (not obligation) to buy/sell at a specific price.\n\n## Types\n\n### Call Option\n- Right to **buy** at strike price\n- Buy calls when bullish\n- Profit when price goes up\n\n### Put Option\n- Right to **sell** at strike price\n- Buy puts when bearish\n- Profit when price goes down\n\n## Key Terms\n- **Strike Price**: The agreed price\n- **Premium**: Cost of the option\n- **Expiry**: When the contract ends\n- **ITM**: In The Money (profitable)\n- **ATM**: At The Money (at strike)\n- **OTM**: Out of The Money (not profitable yet)\n\n## The Greeks\n- **Delta (Δ)**: Rate of price change\n- **Theta (Θ)**: Time decay\n- **Vega (ν)**: Volatility sensitivity\n- **Gamma (Γ)**: Rate of delta change\n\n## Important Warning\n> ⚠️ Options are complex instruments. 90%+ of retail options traders lose money. Start with paper trading and small positions.` },
    ]},
    { title: 'AI & Algorithmic Trading', description: 'Learn how AI and algorithms are transforming stock trading.', icon: '🤖', difficulty: 'advanced', category: 'trading', estimatedTime: '45 min', sortOrder: 20, lessons: [
      { title: 'AI in Trading', type: 'article', estimatedTime: '15 min', sortOrder: 1, content: `# AI & Algo Trading\n\n## How AI is Used in Trading\n\n### 1. Pattern Recognition\n- Candlestick pattern detection\n- Chart pattern recognition\n- Anomaly detection in price/volume\n\n### 2. Sentiment Analysis\n- News sentiment scoring\n- Social media analysis\n- Earnings call transcript analysis\n\n### 3. Predictive Models\n- Price direction prediction\n- Volatility forecasting\n- Sector rotation prediction\n\n### 4. Algorithmic Execution\n- VWAP/TWAP execution\n- Smart order routing\n- High-frequency trading (HFT)\n\n## Building Your Own System\n1. Learn Python + pandas + numpy\n2. Backtest strategies on historical data\n3. Use APIs for live data\n4. Paper trade before going live\n5. Start with simple rules-based systems\n\n## Popular Frameworks\n- **Python**: Backtrader, Zipline, QuantConnect\n- **APIs**: Upstox, Zerodha Kite Connect, Angel One\n\n## ⚠️ Risks\n- Overfitting to historical data\n- Market regime changes\n- Technical failures\n- Regulatory compliance` },
    ]},
  ];
}
