// ═══ PRODUCTION SEED DATA: News Articles ═══

export interface SeedNews {
  title: string; summary: string; content: string; source: string;
  category: string; imageUrl: string; publishedAt: Date;
  aiSentiment: string; aiAnalysis: string; aiImpactScore: number;
  bullishScore: number; bearishScore: number; relatedStockSymbols: string[];
}

const sources = ['Economic Times', 'Moneycontrol', 'LiveMint', 'Business Standard', 'NDTV Profit', 'Bloomberg Quint', 'Reuters India', 'Financial Express', 'Hindu BusinessLine', 'Zeebiz'];
const categories = ['market', 'stocks', 'economy', 'ipo', 'rbi', 'global', 'technology', 'banking', 'commodities', 'crypto', 'budget', 'ai'];

function daysAgo(d: number): Date { const dt = new Date(); dt.setDate(dt.getDate() - d); return dt; }

const newsArticles: SeedNews[] = [
  { title: 'Sensex Rallies 800 Points as FIIs Turn Net Buyers After 3 Months', summary: 'Foreign institutional investors pumped ₹5,200 crore into Indian equities, driving a sharp rally across all sectors. Banking and IT stocks led the gains.', content: 'In a significant reversal of trend, foreign institutional investors (FIIs) turned net buyers in Indian equities after three consecutive months of selling. The BSE Sensex surged 800 points to close at 79,800, while the Nifty 50 gained 245 points to settle at 24,150. Banking stocks were the biggest beneficiaries with HDFC Bank, ICICI Bank, and SBI all gaining over 2%. IT stocks also rallied on expectations of improved deal flows in the coming quarters.', source: 'Economic Times', category: 'market', imageUrl: '/images/news/market-rally.jpg', publishedAt: daysAgo(0), aiSentiment: 'Positive', aiAnalysis: 'Strong FII buying indicates renewed confidence in Indian markets. This trend could sustain if global risk appetite remains healthy.', aiImpactScore: 8, bullishScore: 82, bearishScore: 18, relatedStockSymbols: ['HDFCBANK', 'ICICIBANK', 'SBIN', 'TCS', 'INFY'] },
  { title: 'RBI Holds Repo Rate Steady at 6.5%, Signals Possible Cut in Next Quarter', summary: 'The Reserve Bank of India maintained its benchmark lending rate but changed its stance to neutral, hinting at an accommodative turn.', content: 'The Reserve Bank of India (RBI) kept the repo rate unchanged at 6.5% for the eighth consecutive meeting but changed its policy stance from "withdrawal of accommodation" to "neutral." Governor Shaktikanta Das noted that inflation has moderated and the central bank is now closely monitoring growth dynamics. Market participants interpreted this as a strong signal of a rate cut in the upcoming February policy meeting.', source: 'LiveMint', category: 'rbi', imageUrl: '/images/news/rbi.jpg', publishedAt: daysAgo(1), aiSentiment: 'Positive', aiAnalysis: 'Neutral stance shift is dovish. Banking and real estate stocks should benefit from potential rate cuts.', aiImpactScore: 7, bullishScore: 75, bearishScore: 25, relatedStockSymbols: ['HDFCBANK', 'SBIN', 'ICICIBANK', 'DLF', 'OBEROIRLTY'] },
  { title: 'Reliance Industries Q3 Results: Net Profit Jumps 18% to ₹18,500 Crore', summary: 'Reliance Industries reported strong quarterly results driven by robust performance in retail and Jio segments.', content: 'Reliance Industries Ltd reported an 18% year-on-year increase in consolidated net profit to ₹18,500 crore for Q3 FY25, beating analyst estimates of ₹17,200 crore. Revenue from operations grew 12% to ₹2.45 lakh crore. The Jio Platforms segment reported a 14% increase in ARPU to ₹195, while Reliance Retail saw 22% growth in revenue. The company announced a capex plan of ₹75,000 crore for FY25 focused on 5G expansion and new energy.', source: 'Moneycontrol', category: 'stocks', imageUrl: '/images/news/reliance.jpg', publishedAt: daysAgo(2), aiSentiment: 'Positive', aiAnalysis: 'Strong beat across all segments. Jio ARPU growth and retail expansion are key positives. Stock likely to rerate.', aiImpactScore: 9, bullishScore: 88, bearishScore: 12, relatedStockSymbols: ['RELIANCE'] },
  { title: 'IT Sector Faces Headwinds as US Tech Spending Slows Down', summary: 'Major Indian IT companies may see slower growth as American enterprises cut technology budgets amid recession fears.', content: 'Indian IT services companies are bracing for a challenging quarter as US technology spending shows signs of significant deceleration. Gartner has revised its global IT spending growth forecast from 8% to 5.5% for 2025, citing banking sector stress and AI-related budget reallocation. Analysts expect TCS, Infosys, and HCL Tech to report muted revenue growth of 1-3% in constant currency terms for Q3.', source: 'Business Standard', category: 'technology', imageUrl: '/images/news/it-sector.jpg', publishedAt: daysAgo(3), aiSentiment: 'Negative', aiAnalysis: 'Headwinds for IT sector could persist for 2-3 quarters. Defensive allocation recommended. Selective exposure to companies with strong deal pipelines.', aiImpactScore: -6, bullishScore: 30, bearishScore: 70, relatedStockSymbols: ['TCS', 'INFY', 'HCLTECH', 'WIPRO', 'TECHM'] },
  { title: 'TATA Motors EV Sales Surge 85% in Q3, Dominates Indian EV Market', summary: 'Tata Motors solidified its position as India\'s leading EV manufacturer with record electric vehicle deliveries.', content: 'Tata Motors reported an 85% year-on-year surge in electric vehicle sales during Q3 FY25, delivering 28,500 EVs compared to 15,400 in the same period last year. The Nexon EV remained the bestselling electric car in India, while the newly launched Punch EV crossed 10,000 units. The company now commands a 68% market share in the passenger EV segment. Management guided for 100,000 EV sales in FY25.', source: 'NDTV Profit', category: 'stocks', imageUrl: '/images/news/tata-ev.jpg', publishedAt: daysAgo(4), aiSentiment: 'Positive', aiAnalysis: 'Tata Motors EV leadership is strengthening. Valuation re-rating likely as EV contribution to revenue increases.', aiImpactScore: 7, bullishScore: 80, bearishScore: 20, relatedStockSymbols: ['TATAMOTORS', 'M&M', 'MARUTI'] },
  { title: 'Gold Prices Hit All-Time High of ₹72,000 per 10 Grams Amid Global Uncertainty', summary: 'Safe-haven demand pushes gold to record levels as geopolitical tensions escalate.', content: 'Gold prices in India surged to an all-time high of ₹72,000 per 10 grams, driven by escalating geopolitical tensions in the Middle East and expectations of US Federal Reserve rate cuts. Silver also rallied to ₹85,000 per kg. Analysts expect gold to remain elevated and could test ₹75,000 levels in the near term. Mutual fund inflows into gold ETFs have increased 45% in the past month.', source: 'Reuters India', category: 'commodities', imageUrl: '/images/news/gold.jpg', publishedAt: daysAgo(5), aiSentiment: 'Neutral', aiAnalysis: 'Gold at all-time highs. Good for portfolio diversification but entry at current levels carries near-term risk.', aiImpactScore: 3, bullishScore: 55, bearishScore: 45, relatedStockSymbols: ['TITAN'] },
  { title: 'Adani Group Announces ₹1.2 Lakh Crore Green Energy Investment Plan', summary: 'Adani Green Energy to build 45 GW of renewable capacity by 2030 in India\'s largest clean energy push.', content: 'The Adani Group announced a massive ₹1.2 lakh crore investment plan for green energy infrastructure, aiming to build 45 GW of renewable energy capacity by 2030. The plan includes 30 GW of solar, 10 GW of wind, and 5 GW of hybrid projects across Rajasthan, Gujarat, and Tamil Nadu. Adani Green Energy also secured a $3 billion green bond facility from international investors.', source: 'Bloomberg Quint', category: 'stocks', imageUrl: '/images/news/adani-green.jpg', publishedAt: daysAgo(6), aiSentiment: 'Positive', aiAnalysis: 'Massive capex plan signals strong growth trajectory for Adani Green. Execution risk remains but scale advantage is significant.', aiImpactScore: 6, bullishScore: 72, bearishScore: 28, relatedStockSymbols: ['ADANIENT', 'ADANIGREEN', 'TATAPOWER', 'NTPC'] },
  { title: 'Budget 2025: Government Proposes 0% LTCG on Stocks Held Over 3 Years', summary: 'Finance Minister announces major tax relief for long-term equity investors in the Union Budget.', content: 'In a landmark move, Finance Minister Nirmala Sitharaman proposed eliminating Long-Term Capital Gains (LTCG) tax on equity investments held for more than 3 years. The current 10% LTCG tax on gains exceeding ₹1 lakh will be scrapped, potentially saving investors thousands of crores annually. The move is expected to boost equity market participation and deepen India\'s capital markets.', source: 'Economic Times', category: 'budget', imageUrl: '/images/news/budget.jpg', publishedAt: daysAgo(7), aiSentiment: 'Positive', aiAnalysis: 'Game-changing tax reform. Will significantly boost long-term equity investing and mutual fund flows.', aiImpactScore: 10, bullishScore: 92, bearishScore: 8, relatedStockSymbols: ['HDFCBANK', 'RELIANCE', 'TCS', 'ICICIBANK', 'SBIN'] },
  { title: 'Infosys Wins $2 Billion Deal from European Bank, Largest in Company History', summary: 'Infosys bags its largest-ever deal, a multi-year digital transformation contract with a top European financial institution.', content: 'Infosys announced its largest-ever deal win — a $2 billion, 7-year digital transformation contract with one of Europe\'s top 5 banks. The deal involves cloud migration, AI/ML implementation, and core banking modernization. CEO Salil Parekh said this deal validates Infosys\'s leadership in next-gen digital services and sets a strong foundation for FY26 growth.', source: 'Moneycontrol', category: 'stocks', imageUrl: '/images/news/infosys-deal.jpg', publishedAt: daysAgo(8), aiSentiment: 'Positive', aiAnalysis: 'Mega deal win is a strong confidence booster. Revenue visibility improves significantly for next 2-3 years.', aiImpactScore: 8, bullishScore: 85, bearishScore: 15, relatedStockSymbols: ['INFY', 'TCS', 'HCLTECH', 'WIPRO'] },
  { title: 'SBI Reports Record Q3 Profit of ₹18,000 Crore, NPA at Decade Low', summary: 'State Bank of India delivers stellar results with record profits and best-ever asset quality.', content: 'State Bank of India (SBI) reported a record net profit of ₹18,000 crore for Q3 FY25, up 35% year-on-year. Gross NPA ratio improved to 2.1%, the lowest in over a decade. Net Interest Margin (NIM) remained stable at 3.28%. The bank\'s loan book grew 15% YoY, driven by strong demand in retail and corporate segments.', source: 'Financial Express', category: 'banking', imageUrl: '/images/news/sbi.jpg', publishedAt: daysAgo(9), aiSentiment: 'Positive', aiAnalysis: 'SBI continues to deliver best-in-class results among PSU banks. Valuation remains attractive at 1.5x book.', aiImpactScore: 7, bullishScore: 82, bearishScore: 18, relatedStockSymbols: ['SBIN', 'PNB', 'BANKBARODA', 'CANBK'] },
  { title: 'India VIX Spikes 25% as Global Markets Tumble on US Recession Fears', summary: 'Volatility index surges amid global selloff triggered by weak US jobs data and inverted yield curve.', content: 'India VIX, the fear gauge of the market, spiked 25% to 18.5 levels as global markets sold off sharply following weak US non-farm payroll data and further inversion of the Treasury yield curve. The Nifty fell 350 points, with banking and metal stocks bearing the brunt. Analysts advise caution and suggest hedging existing positions.', source: 'Zeebiz', category: 'market', imageUrl: '/images/news/vix.jpg', publishedAt: daysAgo(10), aiSentiment: 'Negative', aiAnalysis: 'Elevated VIX signals near-term turbulence. Recommended to reduce leveraged positions and increase cash allocation.', aiImpactScore: -7, bullishScore: 22, bearishScore: 78, relatedStockSymbols: ['HDFCBANK', 'TATASTEEL', 'HINDALCO', 'JSWSTEEL'] },
  { title: 'Sun Pharma Gets USFDA Approval for Generic Cancer Drug Worth $800M Market', summary: 'Sun Pharma receives first-to-file approval for a blockbuster oncology drug in the US market.', content: 'Sun Pharmaceutical Industries received USFDA approval for a generic version of a blockbuster cancer drug with an annual US market size of $800 million. As a first-to-file applicant, Sun Pharma will enjoy 180 days of market exclusivity. Analysts estimate this could add ₹2,500-3,000 crore in revenue over the exclusivity period.', source: 'Hindu BusinessLine', category: 'stocks', imageUrl: '/images/news/sunpharma.jpg', publishedAt: daysAgo(11), aiSentiment: 'Positive', aiAnalysis: 'Significant revenue opportunity from first-to-file advantage. Material positive for Sun Pharma\'s specialty portfolio.', aiImpactScore: 8, bullishScore: 85, bearishScore: 15, relatedStockSymbols: ['SUNPHARMA', 'DRREDDY', 'CIPLA', 'LUPIN'] },
  { title: 'HDFC Bank Crosses ₹25 Lakh Crore Market Cap, Joins Elite Global Banking Club', summary: 'HDFC Bank becomes the most valuable bank in emerging markets, surpassing China Construction Bank.', content: 'HDFC Bank crossed ₹25 lakh crore market capitalization, making it the most valuable bank in emerging markets. The stock has rallied 18% in the past quarter on the back of strong loan growth and improving merger synergies. The bank now ranks among the top 10 most valuable banks globally.', source: 'Moneycontrol', category: 'banking', imageUrl: '/images/news/hdfcbank.jpg', publishedAt: daysAgo(12), aiSentiment: 'Positive', aiAnalysis: 'HDFC Bank\'s valuation premium is justified by consistent execution. Post-merger synergies are materializing better than expected.', aiImpactScore: 6, bullishScore: 78, bearishScore: 22, relatedStockSymbols: ['HDFCBANK', 'ICICIBANK', 'KOTAKBANK', 'AXISBANK'] },
  { title: 'Crude Oil Crashes Below $70 as OPEC+ Increases Production Quotas', summary: 'Brent crude oil falls 8% to $68/barrel, benefiting oil-importing nations like India.', content: 'Brent crude oil prices crashed below $70 per barrel for the first time in 18 months after OPEC+ agreed to increase production quotas by 2 million barrels per day starting next quarter. This is a significant positive for India, which imports 85% of its oil needs. Analysts expect this to save India $15-20 billion annually in oil imports and ease inflationary pressures.', source: 'Reuters India', category: 'commodities', imageUrl: '/images/news/crude-oil.jpg', publishedAt: daysAgo(13), aiSentiment: 'Positive', aiAnalysis: 'Lower crude is strongly positive for Indian economy, OMCs, and airlines. Negative for upstream companies like ONGC.', aiImpactScore: 7, bullishScore: 75, bearishScore: 25, relatedStockSymbols: ['BPCL', 'IOC', 'ONGC', 'INDIGO', 'RELIANCE'] },
  { title: 'Maruti Suzuki Launches India\'s First Mass-Market Electric SUV at ₹12 Lakh', summary: 'Maruti disrupts the EV market with an aggressively priced electric SUV, challenging Tata and MG.', content: 'Maruti Suzuki India launched the eVitara, India\'s first mass-market electric SUV, at an introductory price of ₹12.49 lakh. The vehicle offers a range of 500 km on a single charge and comes with Suzuki\'s proprietary battery technology. Pre-bookings crossed 25,000 units within the first week. This entry is expected to disrupt the EV market dominated by Tata Motors.', source: 'NDTV Profit', category: 'stocks', imageUrl: '/images/news/maruti-ev.jpg', publishedAt: daysAgo(14), aiSentiment: 'Positive', aiAnalysis: 'Maruti\'s aggressive EV pricing could accelerate India\'s EV adoption. Threat to Tata Motors\' EV dominance.', aiImpactScore: 8, bullishScore: 80, bearishScore: 20, relatedStockSymbols: ['MARUTI', 'TATAMOTORS', 'M&M'] },
  { title: 'India GDP Growth Accelerates to 7.8% in Q2, Beats All Estimates', summary: 'India remains the fastest-growing major economy, outpacing China for the 6th consecutive quarter.', content: 'India\'s GDP growth accelerated to 7.8% in Q2 FY25, significantly beating the consensus estimate of 6.7% and outpacing China\'s 4.7% growth. Manufacturing sector growth was the standout at 9.3%, while services grew 7.1%. The government revised its full-year growth estimate to 7.5% from earlier 7.0%.', source: 'Economic Times', category: 'economy', imageUrl: '/images/news/gdp.jpg', publishedAt: daysAgo(15), aiSentiment: 'Positive', aiAnalysis: 'Strong GDP growth supports equity market upside. Consumption and infrastructure plays should benefit the most.', aiImpactScore: 9, bullishScore: 88, bearishScore: 12, relatedStockSymbols: ['RELIANCE', 'LT', 'HDFCBANK', 'MARUTI', 'TITAN'] },
  { title: 'AI Revolution: Indian IT Companies to Invest $5 Billion in Generative AI', summary: 'TCS, Infosys, Wipro, and HCL announce massive AI investments to stay competitive in the GenAI era.', content: 'India\'s top IT companies have collectively committed $5 billion to generative AI initiatives over the next three years. TCS announced the creation of 10 new AI labs, Infosys launched its Topaz AI platform, Wipro introduced the ai360 initiative, and HCL Tech revealed plans for 25,000 AI-trained consultants. The companies expect AI to contribute 15-20% of revenue by FY27.', source: 'Business Standard', category: 'ai', imageUrl: '/images/news/ai-it.jpg', publishedAt: daysAgo(16), aiSentiment: 'Positive', aiAnalysis: 'AI investments position Indian IT for the next growth wave. Companies with strong AI capabilities will command premium valuations.', aiImpactScore: 7, bullishScore: 78, bearishScore: 22, relatedStockSymbols: ['TCS', 'INFY', 'WIPRO', 'HCLTECH', 'TECHM', 'LTIM'] },
  { title: 'IPO Boom: 8 Companies Line Up for ₹15,000 Crore Worth of IPOs This Month', summary: 'Record IPO pipeline as investor appetite for primary market offerings remains robust.', content: 'Eight companies have filed for IPOs worth a combined ₹15,000 crore this month, signaling the continued strength of India\'s primary market. Notable names include a fintech unicorn, two EV component makers, and a specialty chemicals company. Grey market premiums range from 25% to 85%, indicating strong demand.', source: 'Moneycontrol', category: 'ipo', imageUrl: '/images/news/ipo.jpg', publishedAt: daysAgo(17), aiSentiment: 'Neutral', aiAnalysis: 'Heavy IPO pipeline could divert funds from secondary markets in the short term but signals healthy market ecosystem.', aiImpactScore: 2, bullishScore: 55, bearishScore: 45, relatedStockSymbols: [] },
  { title: 'Nifty Bank Index Hits Record High as ICICI Bank, Kotak Cross Key Resistance', summary: 'Banking index surges past 52,000 as private banks lead the charge with improving asset quality.', content: 'The Nifty Bank Index hit a record high of 52,345, driven by strong buying in private sector banks. ICICI Bank crossed ₹1,300 for the first time while Kotak Mahindra Bank broke above its 200-day moving average. Analysts attribute the rally to improving asset quality metrics, strong credit growth of 16%, and expectations of NIM expansion.', source: 'Zeebiz', category: 'market', imageUrl: '/images/news/bank-nifty.jpg', publishedAt: daysAgo(18), aiSentiment: 'Positive', aiAnalysis: 'Banking sector breakout is technically significant. Momentum likely to continue as fundamentals remain strong.', aiImpactScore: 6, bullishScore: 80, bearishScore: 20, relatedStockSymbols: ['ICICIBANK', 'KOTAKBANK', 'HDFCBANK', 'AXISBANK', 'INDUSINDBK'] },
  { title: 'Wipro Announces Surprise Bonus Shares in 1:1 Ratio', summary: 'Wipro board approves one bonus share for every share held, rewarding long-term shareholders.', content: 'Wipro Ltd surprised the market by announcing a 1:1 bonus share issue, meaning shareholders will receive one additional share for every share held. The record date has been set for next month. The stock surged 8% on the announcement. This is Wipro\'s first bonus issue in 5 years.', source: 'Financial Express', category: 'stocks', imageUrl: '/images/news/wipro.jpg', publishedAt: daysAgo(19), aiSentiment: 'Positive', aiAnalysis: 'Bonus issue signals management confidence. Stock may see sustained buying interest from retail investors.', aiImpactScore: 5, bullishScore: 72, bearishScore: 28, relatedStockSymbols: ['WIPRO', 'TCS', 'INFY'] },
  { title: 'Power Sector Rally: NTPC, Power Grid Surge as India Targets 500 GW Renewable Capacity', summary: 'Power stocks rally as government announces accelerated renewable energy targets.', content: 'Power sector stocks surged with NTPC gaining 5% and Power Grid rising 4% after the government revised its renewable energy target to 500 GW by 2030, up from the earlier 450 GW target. Additional allocation of ₹50,000 crore for green energy infrastructure was announced. NTPC Green Energy IPO is also expected to list at a significant premium.', source: 'LiveMint', category: 'stocks', imageUrl: '/images/news/power.jpg', publishedAt: daysAgo(20), aiSentiment: 'Positive', aiAnalysis: 'Power sector is a structural growth story. NTPC and Power Grid offer the best risk-reward in the space.', aiImpactScore: 7, bullishScore: 82, bearishScore: 18, relatedStockSymbols: ['NTPC', 'POWERGRID', 'TATAPOWER', 'ADANIGREEN', 'NHPC'] },
  { title: 'Defence Stocks Soar as Government Approves ₹2.5 Lakh Crore Procurement Plan', summary: 'HAL, BEL, and Cochin Shipyard hit 52-week highs on massive defence order expectations.', content: 'Defence stocks witnessed a sharp rally with HAL, BEL, and Cochin Shipyard hitting 52-week highs after the Defence Acquisition Council approved procurement worth ₹2.5 lakh crore. The orders include light combat aircraft, naval frigates, advanced radar systems, and missile systems. HAL alone is expected to receive orders worth ₹80,000 crore over the next 3 years.', source: 'Economic Times', category: 'stocks', imageUrl: '/images/news/defence.jpg', publishedAt: daysAgo(21), aiSentiment: 'Positive', aiAnalysis: 'Defence sector offers multi-year visibility. HAL and BEL are best positioned to benefit from the procurement plan.', aiImpactScore: 8, bullishScore: 85, bearishScore: 15, relatedStockSymbols: ['HAL', 'BEL', 'COCHINSHIP'] },
  { title: 'Cryptocurrency Market Crashes 20% as SEC Announces Stricter Regulations', summary: 'Bitcoin falls below $50,000 as regulatory crackdown fears grip the crypto market globally.', content: 'The cryptocurrency market witnessed a sharp 20% correction with Bitcoin falling below $50,000 for the first time in 6 months. The selloff was triggered by the SEC announcing stricter regulations on crypto exchanges and DeFi protocols. Ethereum dropped 25%, while altcoins fell 30-50%. Indian crypto exchange volumes declined 60% in the past week.', source: 'Bloomberg Quint', category: 'crypto', imageUrl: '/images/news/crypto.jpg', publishedAt: daysAgo(22), aiSentiment: 'Negative', aiAnalysis: 'Crypto regulatory risk remains high. Traditional equity markets may benefit from capital rotation out of crypto.', aiImpactScore: -4, bullishScore: 20, bearishScore: 80, relatedStockSymbols: [] },
  { title: 'US Fed Signals Rate Cuts in March 2025, Global Markets Rally', summary: 'Federal Reserve Chair signals 3 rate cuts in 2025, boosting emerging market sentiment.', content: 'Federal Reserve Chair Jerome Powell signaled that the central bank could begin cutting interest rates as early as March 2025, with three 25-basis-point cuts expected through the year. Global markets rallied on the news, with the Dow Jones surging 500 points. Emerging market currencies and equities strengthened, with the Indian rupee appreciating to 82.5 against the dollar.', source: 'Reuters India', category: 'global', imageUrl: '/images/news/fed.jpg', publishedAt: daysAgo(23), aiSentiment: 'Positive', aiAnalysis: 'US rate cuts are strongly positive for emerging markets. FII flows to India likely to accelerate.', aiImpactScore: 8, bullishScore: 85, bearishScore: 15, relatedStockSymbols: ['HDFCBANK', 'TCS', 'RELIANCE', 'INFY'] },
  { title: 'ITC Demerger: Hotels Business to List Separately, Unlocking ₹40,000 Crore Value', summary: 'ITC announces demerger of its hotels business, creating a separate listed entity.', content: 'ITC Ltd announced the demerger of its hotels business into a separately listed entity, potentially unlocking ₹40,000 crore in shareholder value. ITC will retain a 40% stake in the hotels business. The demerger is expected to be completed within 12 months. Analysts view this as a significant re-rating catalyst for ITC, as the FMCG and hotels businesses were previously trading at a conglomerate discount.', source: 'Moneycontrol', category: 'stocks', imageUrl: '/images/news/itc.jpg', publishedAt: daysAgo(24), aiSentiment: 'Positive', aiAnalysis: 'Demerger removes conglomerate discount. ITC FMCG business alone could command a PE of 35-40x.', aiImpactScore: 8, bullishScore: 82, bearishScore: 18, relatedStockSymbols: ['ITC'] },
  { title: 'Asian Paints Market Share Under Threat as Birla Opus Disrupts Paint Industry', summary: 'Grasim\'s Birla Opus brand gains rapid market share, posing a competitive threat to Asian Paints.', content: 'Asian Paints is facing its toughest competitive challenge in decades as Grasim Industries\' Birla Opus paint brand captures 3% market share within just 6 months of launch. Birla Opus has been offering 15-20% lower prices on comparable products. Asian Paints management acknowledged the competitive pressure and announced ₹2,000 crore in marketing spend to defend its market position.', source: 'Business Standard', category: 'stocks', imageUrl: '/images/news/asian-paints.jpg', publishedAt: daysAgo(25), aiSentiment: 'Negative', aiAnalysis: 'Competitive disruption is a real threat to Asian Paints\' margins. Stock could see de-rating if market share losses persist.', aiImpactScore: -6, bullishScore: 28, bearishScore: 72, relatedStockSymbols: ['ASIANPAINT', 'GRASIM', 'PIDILITIND'] },
  { title: 'Bajaj Finance AUM Crosses ₹3 Lakh Crore, Eyes ₹5 Lakh Crore by FY27', summary: 'Bajaj Finance reports record AUM growth driven by digital lending and new product launches.', content: 'Bajaj Finance crossed the ₹3 lakh crore assets under management (AUM) milestone, becoming the largest NBFC in India. The company added ₹12,000 crore in new loans during the quarter, with digital channels contributing 65% of new customer acquisition. Management guided for ₹5 lakh crore AUM by FY27.', source: 'NDTV Profit', category: 'stocks', imageUrl: '/images/news/bajaj-finance.jpg', publishedAt: daysAgo(26), aiSentiment: 'Positive', aiAnalysis: 'Bajaj Finance execution remains best-in-class. Growth visibility is strong and asset quality is stable.', aiImpactScore: 7, bullishScore: 80, bearishScore: 20, relatedStockSymbols: ['BAJFINANCE', 'BAJAJFINSV', 'CHOLAFIN', 'SHRIRAMFIN'] },
];

// Generate more news programmatically
function generateMoreNews(count: number): SeedNews[] {
  const templates = [
    { title: '{COMPANY} Reports Strong Q{Q} Results, Beats Street Estimates', category: 'stocks', sentiment: 'Positive', impact: 6 },
    { title: '{SECTOR} Sector Under Pressure Amid Global Headwinds', category: 'market', sentiment: 'Negative', impact: -4 },
    { title: 'FIIs {ACTION} ₹{AMT} Crore in Indian Equities on {DAY}', category: 'market', sentiment: 'Neutral', impact: 3 },
    { title: '{COMPANY} Board Approves ₹{AMT} Crore Buyback Program', category: 'stocks', sentiment: 'Positive', impact: 5 },
    { title: 'Mutual Fund SIP Flows Hit Record ₹{AMT} Crore in {MONTH}', category: 'market', sentiment: 'Positive', impact: 4 },
    { title: '{COMPANY} Partners with {PARTNER} for AI-Powered Solutions', category: 'ai', sentiment: 'Positive', impact: 5 },
    { title: 'Rupee {DIRECTION} Against Dollar as {REASON}', category: 'economy', sentiment: 'Neutral', impact: 2 },
    { title: '{SECTOR} Stocks Rally as Government Announces Policy Support', category: 'stocks', sentiment: 'Positive', impact: 6 },
    { title: '{COMPANY} Launches New Product Line, Targets ₹{AMT} Crore Revenue', category: 'stocks', sentiment: 'Positive', impact: 4 },
    { title: 'Global Markets Mixed as China Data Disappoints, US Strong', category: 'global', sentiment: 'Neutral', impact: 1 },
  ];
  const companies = ['Reliance', 'TCS', 'HDFC Bank', 'Infosys', 'ICICI Bank', 'ITC', 'SBI', 'Bharti Airtel', 'HCL Tech', 'Wipro', 'L&T', 'Bajaj Finance', 'Titan', 'Sun Pharma', 'Maruti'];
  const sectorsList = ['Banking', 'IT', 'Pharma', 'Auto', 'FMCG', 'Metal', 'Infra', 'Power', 'Defence', 'Real Estate'];
  const result: SeedNews[] = [];
  
  for (let i = 0; i < count; i++) {
    const tmpl = templates[i % templates.length];
    const company = companies[i % companies.length];
    const sector = sectorsList[i % sectorsList.length];
    const title = tmpl.title.replace('{COMPANY}', company).replace('{SECTOR}', sector).replace('{Q}', `${(i % 4) + 1}`).replace('{AMT}', `${1000 + i * 200}`).replace('{ACTION}', i % 2 === 0 ? 'Buy' : 'Sell').replace('{DAY}', 'Monday').replace('{MONTH}', 'December').replace('{PARTNER}', 'Microsoft').replace('{DIRECTION}', i % 2 === 0 ? 'Strengthens' : 'Weakens').replace('{REASON}', 'FII inflows');
    
    result.push({
      title,
      summary: `${title}. Market participants closely watching developments.`,
      content: `${title}. This development has significant implications for the broader market. Analysts are divided on the impact, with some viewing it as a positive catalyst while others remain cautious. Market volumes have picked up in response to this news.`,
      source: sources[i % sources.length],
      category: tmpl.category,
      imageUrl: `/images/news/generic-${(i % 5) + 1}.jpg`,
      publishedAt: daysAgo(27 + i),
      aiSentiment: tmpl.sentiment,
      aiAnalysis: `${tmpl.sentiment === 'Positive' ? 'Favorable' : tmpl.sentiment === 'Negative' ? 'Concerning' : 'Developing'} situation. Monitor closely for further developments. ${tmpl.sentiment === 'Positive' ? 'Could drive upside momentum.' : tmpl.sentiment === 'Negative' ? 'Caution warranted.' : 'Wait for clarity.'}`,
      aiImpactScore: tmpl.impact,
      bullishScore: tmpl.sentiment === 'Positive' ? 65 + (i % 20) : tmpl.sentiment === 'Negative' ? 20 + (i % 15) : 45 + (i % 15),
      bearishScore: tmpl.sentiment === 'Positive' ? 35 - (i % 20) : tmpl.sentiment === 'Negative' ? 80 - (i % 15) : 55 - (i % 15),
      relatedStockSymbols: [company.toUpperCase().replace(/ /g, '').slice(0, 10)],
    });
  }
  return result;
}

export function generateAllNews(): SeedNews[] {
  return [...newsArticles, ...generateMoreNews(200)];
}
